### ISSUE TITLE
Installation of plugin crashes Grafana in Home Assistant

### ISSUE THREAD

**Issue by jbrepogmailcom** [diebietse/grafana-mqtt#1]
Hello, when I add plugin:
```
plugins:
  - diebietse-mqtt
```
in Grafana configuration in Home Assistant, grafana crashes and does not start:
```
Error: ✗ Plugin not found (Grafana v8.3.4 linux-amd64)
[13:11:04] FATAL: Failed installing Grafana plugin: diebietse-mqtt
[cont-init.d] grafana.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```
I guess it looks for plugins at Grafana web...

**Comment by hpdvanwyk** [comment]
I think you are right. This plugin needs to be installed manually since it is not hosted on the Grafana site. I have never installed Grafana with Home Assistant so I can't really help there.

I created this plugin because I wanted Grafana gauges that can update live like Home Assistant gauges so you could try using one of those if this is for a Home Assistant dashboard.
